spring:
  # \u6570\u636E\u6E90\u914D\u7F6E
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///springboot_web_demo?charactEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    servlet:
      multipart:
        enabled: true
        max-file-size: 2000MB
        max-request-size: 2000MB
# \u670D\u52A1\u5668
server:
  port: 8081
# \u63A7\u5236\u53F0\u6253\u5370sql\u8BED\u53E5
logging:
  level:
    com.hu: debug
