# 服务端口
server:
  port: 8081
spring:
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_web_demo?charactEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    servlet:
      multipart:
        enabled: true
        max-file-size: 2000MB
        max-request-size: 2000MB
  # 静态资源配置
  resources:
    static-locations: classpath:/templates/, classpath:/static/
  # 关闭模板引擎缓存
  thymeleaf:
    cache: false
# 日志输出
logging:
  level:
    com.hu: debug